version: '3.8'

services:
  db:
    image: rverat/ms-core-user-v1-1.0.1  #db image if you create image of your database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thedevlair

  app:
    image: rverat/ms-core-user-v1-1.0.0 #spring boot api image
    ports:
      - 9082:9082
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/thedevlair
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
